// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sVo0wzx1GeEeLr_svmxdi9vlV0IoB24',
    appId: '1:397115646073:android:c9c5a14a13c4332a5af4a8',
    messagingSenderId: '397115646073',
    projectId: 'movie-2d9e0',
    storageBucket: 'movie-2d9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzvDAMcgCcOcY-deeteA-NxjsWgXSoa9o',
    appId: '1:397115646073:ios:a3b9f60e06c346ac5af4a8',
    messagingSenderId: '397115646073',
    projectId: 'movie-2d9e0',
    storageBucket: 'movie-2d9e0.appspot.com',
    iosBundleId: 'ddy.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzvDAMcgCcOcY-deeteA-NxjsWgXSoa9o',
    appId: '1:397115646073:ios:a6d6760d4379119e5af4a8',
    messagingSenderId: '397115646073',
    projectId: 'movie-2d9e0',
    storageBucket: 'movie-2d9e0.appspot.com',
    iosBundleId: 'ddy.example.movieApp.RunnerTests',
  );
}
